import type { ContactRecord } from '../types/domain';

export const contacts: ContactRecord[] = [
  {
    id: 'marcus-sterling',
    initials: 'MS',
    name: 'Marcus Sterling',
    role: 'Vendor',
    secondaryRoles: [],
    address: 'The Glass House, Surrey',
    email: 'sterling@marcus.io',
    phone: '+44 7700 900 456',
    lastActivity: 'Oct 21, 2023',
    lastActivityNote: 'Site Visit: Surrey Estate',
    pendingAction: 'None Pending',
    pendingTone: 'neutral',
  },
  {
    id: 'victoria-sterling',
    initials: 'VS',
    name: 'Victoria Sterling',
    role: 'Purchaser',
    secondaryRoles: [],
    address: 'Belgravia, London SW1W',
    email: 'v.sterling@premium.com',
    phone: '+44 20 7946 0123',
    lastActivity: 'Oct 24, 2023',
    lastActivityNote: 'Portfolio Review Call',
    pendingAction: 'Contract Renewal',
    pendingTone: 'danger',
  },
  {
    id: 'sterling-holdings',
    initials: 'SH',
    name: 'Sterling Real Estate Holdings Ltd',
    role: 'Company / Vendor',
    secondaryRoles: [],
    address: 'The Glass House, Weybridge, Surrey, KT13',
    email: 'corporate@sterling.io',
    phone: 'Victoria Sterling (MD) +44 20 7946 0123',
    lastActivity: 'Today',
    lastActivityNote: 'Onboarding & AML Audit',
    pendingAction: 'Corporate AML & Board Resolution',
    pendingTone: 'warning',
  },
  {
    id: 'julianne-deluca',
    initials: 'JL',
    name: 'Julianne de Luca',
    role: 'Tenant',
    secondaryRoles: ['Purchaser'],
    address: 'Skyline Loft, Manchester',
    email: 'julianne@deluca.com',
    phone: '+44 7700 900 789',
    lastActivity: 'Yesterday',
    lastActivityNote: 'Email: Mortgage Docs',
    pendingAction: 'Appraisal Scheduled',
    pendingTone: 'warning',
  },
  {
    id: 'alistair-vaughn',
    initials: 'AV',
    name: 'Dr. Alistair Vaughn',
    role: 'Landlord',
    secondaryRoles: [],
    address: "Regent's Park Crescent, London NW1",
    email: 'a.vaughn@harley.co.uk',
    phone: '+44 7700 900 888',
    lastActivity: 'Oct 18, 2023',
    lastActivityNote: 'Market Valuation Sent',
    pendingAction: 'None Pending',
    pendingTone: 'warning',
  },
  {
    id: 'elena-rodriguez',
    initials: 'ER',
    name: 'Elena Rodriguez',
    role: 'Tenant',
    secondaryRoles: ['High Urgency'],
    address: 'Kensington, London W8',
    email: 'erod@globalassets.co',
    phone: '+44 7700 900 312',
    lastActivity: '3 days ago',
    lastActivityNote: 'Email: Availability',
    pendingAction: '3 Tasks Pending',
    pendingTone: 'warning',
  },
];
