import type {
  ContactRecord,
  DashboardSummary,
  LeaseRecord,
  MaintenanceRecord,
  NotificationRecord,
  PaymentRecord,
  PropertyRecord,
  TenantRecord,
  User,
} from '../types/domain';

export const demoUser: User = {
  id: 'user-riyaz',
  email: 'admin@jfcrm.local',
  firstName: 'Riyaz',
  lastName: 'Admin',
  role: 'SUPER_ADMIN',
  phone: '+44 20 7946 0100',
  isActive: true,
};

export const contacts: ContactRecord[] = [
  {
    id: 'marcus-sterling',
    initials: 'MS',
    name: 'Marcus Sterling',
    role: 'Vendor',
    secondaryRoles: [],
    address: 'The Glass House, Surrey',
    email: 'sterling@marcus.io',
    phone: '+44 7700 900 456',
    lastActivity: 'Oct 21, 2023',
    lastActivityNote: 'Site Visit: Surrey Estate',
    pendingAction: 'None Pending',
    pendingTone: 'neutral',
  },
  {
    id: 'victoria-sterling',
    initials: 'VS',
    name: 'Victoria Sterling',
    role: 'Purchaser',
    secondaryRoles: [],
    address: 'Belgravia, London SW1W',
    email: 'v.sterling@premium.com',
    phone: '+44 20 7946 0123',
    lastActivity: 'Oct 24, 2023',
    lastActivityNote: 'Portfolio Review Call',
    pendingAction: 'Contract Renewal',
    pendingTone: 'danger',
  },
  {
    id: 'sterling-holdings',
    initials: 'SH',
    name: 'Sterling Real Estate Holdings Ltd',
    role: 'Company / Vendor',
    secondaryRoles: [],
    address: 'The Glass House, Weybridge, Surrey, KT13',
    email: 'corporate@sterling.io',
    phone: 'Victoria Sterling (MD) +44 20 7946 0123',
    lastActivity: 'Today',
    lastActivityNote: 'Onboarding & AML Audit',
    pendingAction: 'Corporate AML & Board Resolution',
    pendingTone: 'warning',
  },
  {
    id: 'julianne-deluca',
    initials: 'JL',
    name: 'Julianne de Luca',
    role: 'Tenant',
    secondaryRoles: ['Purchaser'],
    address: 'Skyline Loft, Manchester',
    email: 'julianne@deluca.com',
    phone: '+44 7700 900 789',
    lastActivity: 'Yesterday',
    lastActivityNote: 'Email: Mortgage Docs',
    pendingAction: 'Appraisal Scheduled',
    pendingTone: 'warning',
  },
  {
    id: 'alistair-vaughn',
    initials: 'AV',
    name: 'Dr. Alistair Vaughn',
    role: 'Landlord',
    secondaryRoles: [],
    address: "Regent's Park Crescent, London NW1",
    email: 'a.vaughn@harley.co.uk',
    phone: '+44 7700 900 888',
    lastActivity: 'Oct 18, 2023',
    lastActivityNote: 'Market Valuation Sent',
    pendingAction: 'None Pending',
    pendingTone: 'warning',
  },
  {
    id: 'elena-rodriguez',
    initials: 'ER',
    name: 'Elena Rodriguez',
    role: 'Tenant',
    secondaryRoles: ['High Urgency'],
    address: 'Kensington, London W8',
    email: 'erod@globalassets.co',
    phone: '+44 7700 900 312',
    lastActivity: '3 days ago',
    lastActivityNote: 'Email: Availability',
    pendingAction: '3 Tasks Pending',
    pendingTone: 'warning',
  },
];

export const properties: PropertyRecord[] = [
  {
    id: 'property-glass-house',
    reference: 'JF-GU5-001',
    title: 'The Glass House',
    type: 'HOUSE',
    status: 'OCCUPIED',
    addressLine1: '14 Cheltenham Place',
    city: 'Wilmslow',
    postcode: 'SK9 4AA',
    bedrooms: 5,
    bathrooms: 4,
    rentAmount: 4200,
    depositAmount: 8400,
    askingPrice: 4000000,
    ownerName: 'Marcus Sterling',
  },
  {
    id: 'property-skyline-loft',
    reference: 'JF-MCR-014',
    title: 'Skyline Loft',
    type: 'FLAT',
    status: 'AVAILABLE',
    addressLine1: '21 Deansgate',
    city: 'Manchester',
    postcode: 'M3 2BW',
    bedrooms: 2,
    bathrooms: 2,
    rentAmount: 2150,
    depositAmount: 4300,
    ownerName: 'Julianne de Luca',
  },
  {
    id: 'property-regents',
    reference: 'JF-NW1-008',
    title: "Regent's Park Crescent",
    type: 'TOWNHOUSE',
    status: 'UNDER_MAINTENANCE',
    addressLine1: "18 Regent's Park Crescent",
    city: 'London',
    postcode: 'NW1 7EE',
    bedrooms: 4,
    bathrooms: 3,
    rentAmount: 6800,
    depositAmount: 13600,
    ownerName: 'Dr. Alistair Vaughn',
  },
];

export const tenants: TenantRecord[] = [
  {
    id: 'tenant-victoria',
    firstName: 'Victoria',
    lastName: 'Sterling',
    email: 'victoria.sterling@example.com',
    phone: '+44 20 7946 0123',
    status: 'ACTIVE',
    currentProperty: properties[0],
  },
  {
    id: 'tenant-julianne',
    firstName: 'Julianne',
    lastName: 'de Luca',
    email: 'julianne@deluca.com',
    phone: '+44 7700 900 789',
    status: 'APPLICANT',
    currentProperty: properties[1],
  },
];

export const leases: LeaseRecord[] = [
  {
    id: 'lease-glass-house',
    property: properties[0],
    tenant: tenants[0],
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    rentAmount: 4200,
    status: 'ACTIVE',
  },
  {
    id: 'lease-regents',
    property: properties[2],
    tenant: tenants[1],
    startDate: '2025-07-01',
    endDate: '2026-07-01',
    rentAmount: 6800,
    status: 'EXPIRING',
  },
];

export const payments: PaymentRecord[] = [
  {
    id: 'payment-may',
    reference: 'PAY-2026-0001',
    property: properties[0],
    tenant: tenants[0],
    amount: 4200,
    dueDate: '2026-05-01',
    paidAt: '2026-05-02',
    status: 'PAID',
    method: 'BANK_TRANSFER',
  },
  {
    id: 'payment-june',
    reference: 'PAY-2026-0002',
    property: properties[0],
    tenant: tenants[0],
    amount: 4200,
    dueDate: '2026-06-01',
    status: 'PENDING',
  },
];

export const maintenance: MaintenanceRecord[] = [
  {
    id: 'ticket-extractor',
    title: 'Kitchen extractor service',
    description: 'Vendor reported noise during valuation follow-up.',
    property: properties[0],
    tenant: tenants[0],
    assignee: {
      id: 'agent-alexander',
      firstName: 'Alexander',
      lastName: 'Thorne',
      email: 'alexander.thorne@jfcrm.local',
      role: 'PROPERTY_MANAGER',
    },
    priority: 'MEDIUM',
    status: 'ASSIGNED',
    dueDate: '2026-05-29',
  },
  {
    id: 'ticket-safety',
    title: 'Pre-let safety inspection',
    description: 'Schedule gas and electrical inspection before listing push.',
    property: properties[1],
    priority: 'HIGH',
    status: 'OPEN',
  },
];

export const notifications: NotificationRecord[] = [
  {
    id: 'notification-renewal',
    title: 'Lease renewal window',
    message: 'The Glass House lease needs renewal review inside 60 days.',
    type: 'TASK',
    createdAt: '2026-05-25T10:00:00.000Z',
    link: '/leases',
  },
  {
    id: 'notification-payment',
    title: 'Payment reminder ready',
    message: 'June rent reminder is queued for Victoria Sterling.',
    type: 'INFO',
    createdAt: '2026-05-25T11:00:00.000Z',
    link: '/payments',
  },
];

export const users: User[] = [
  demoUser,
  {
    id: 'agent-alexander',
    email: 'alexander.thorne@jfcrm.local',
    firstName: 'Alexander',
    lastName: 'Thorne',
    role: 'PROPERTY_MANAGER',
    phone: '+44 7700 900 456',
    isActive: true,
  },
  {
    id: 'accounts-amelia',
    email: 'amelia.accounts@jfcrm.local',
    firstName: 'Amelia',
    lastName: 'Brooks',
    role: 'ACCOUNTANT',
    isActive: true,
  },
];

export const dashboardSummary: DashboardSummary = {
  kpis: {
    properties: 128,
    occupiedProperties: 111,
    occupancyRate: 87,
    activeLeases: 104,
    expiringLeases: 12,
    overduePayments: 8,
    monthlyRevenue: 81200,
    openTickets: 17,
  },
  analytics: {
    revenueTrend: [
      { label: 'Jan', value: 68000 },
      { label: 'Feb', value: 72000 },
      { label: 'Mar', value: 76000 },
      { label: 'Apr', value: 73500 },
      { label: 'May', value: 81200 },
    ],
    maintenanceByStatus: [
      { label: 'Open', value: 9 },
      { label: 'Assigned', value: 8 },
      { label: 'Completed', value: 19 },
    ],
  },
  recentActivity: [
    {
      id: 'activity-valuation',
      title: 'Valuation booked',
      message: 'Alexander Thorne scheduled a property valuation appointment.',
      type: 'PROPERTY',
      createdAt: '2026-05-25T09:00:00.000Z',
    },
    {
      id: 'activity-payment',
      title: 'Rent reconciled',
      message: 'May rent payment was reconciled for The Glass House.',
      type: 'PAYMENT',
      createdAt: '2026-05-24T14:00:00.000Z',
    },
    {
      id: 'activity-ticket',
      title: 'Maintenance assigned',
      message: 'Kitchen extractor service assigned to Alexander Thorne.',
      type: 'MAINTENANCE',
      createdAt: '2026-05-23T16:30:00.000Z',
    },
  ],
};
